// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_service

import (
	context "context"
	entity "medical-webhook/internal/domain/line/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockEquipmentService is an autogenerated mock type for the EquipmentService type
type MockEquipmentService struct {
	mock.Mock
}

type MockEquipmentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEquipmentService) EXPECT() *MockEquipmentService_Expecter {
	return &MockEquipmentService_Expecter{mock: &_m.Mock}
}

// CountEquipments provides a mock function with given fields: ctx
func (_m *MockEquipmentService) CountEquipments(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountEquipments")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_CountEquipments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEquipments'
type MockEquipmentService_CountEquipments_Call struct {
	*mock.Call
}

// CountEquipments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentService_Expecter) CountEquipments(ctx interface{}) *MockEquipmentService_CountEquipments_Call {
	return &MockEquipmentService_CountEquipments_Call{Call: _e.mock.On("CountEquipments", ctx)}
}

func (_c *MockEquipmentService_CountEquipments_Call) Run(run func(ctx context.Context)) *MockEquipmentService_CountEquipments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEquipmentService_CountEquipments_Call) Return(_a0 int64, _a1 error) *MockEquipmentService_CountEquipments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_CountEquipments_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockEquipmentService_CountEquipments_Call {
	_c.Call.Return(run)
	return _c
}

// CountEquipmentsWithFilter provides a mock function with given fields: ctx, status, search, expiryFilter, categoryID
func (_m *MockEquipmentService) CountEquipmentsWithFilter(ctx context.Context, status string, search string, expiryFilter string, categoryID string) (int64, error) {
	ret := _m.Called(ctx, status, search, expiryFilter, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for CountEquipmentsWithFilter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (int64, error)); ok {
		return rf(ctx, status, search, expiryFilter, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) int64); ok {
		r0 = rf(ctx, status, search, expiryFilter, categoryID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, status, search, expiryFilter, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_CountEquipmentsWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEquipmentsWithFilter'
type MockEquipmentService_CountEquipmentsWithFilter_Call struct {
	*mock.Call
}

// CountEquipmentsWithFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - search string
//   - expiryFilter string
//   - categoryID string
func (_e *MockEquipmentService_Expecter) CountEquipmentsWithFilter(ctx interface{}, status interface{}, search interface{}, expiryFilter interface{}, categoryID interface{}) *MockEquipmentService_CountEquipmentsWithFilter_Call {
	return &MockEquipmentService_CountEquipmentsWithFilter_Call{Call: _e.mock.On("CountEquipmentsWithFilter", ctx, status, search, expiryFilter, categoryID)}
}

func (_c *MockEquipmentService_CountEquipmentsWithFilter_Call) Run(run func(ctx context.Context, status string, search string, expiryFilter string, categoryID string)) *MockEquipmentService_CountEquipmentsWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockEquipmentService_CountEquipmentsWithFilter_Call) Return(_a0 int64, _a1 error) *MockEquipmentService_CountEquipmentsWithFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_CountEquipmentsWithFilter_Call) RunAndReturn(run func(context.Context, string, string, string, string) (int64, error)) *MockEquipmentService_CountEquipmentsWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEquipment provides a mock function with given fields: ctx, equipment
func (_m *MockEquipmentService) CreateEquipment(ctx context.Context, equipment *entity.Equipment) error {
	ret := _m.Called(ctx, equipment)

	if len(ret) == 0 {
		panic("no return value specified for CreateEquipment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Equipment) error); ok {
		r0 = rf(ctx, equipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentService_CreateEquipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEquipment'
type MockEquipmentService_CreateEquipment_Call struct {
	*mock.Call
}

// CreateEquipment is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment *entity.Equipment
func (_e *MockEquipmentService_Expecter) CreateEquipment(ctx interface{}, equipment interface{}) *MockEquipmentService_CreateEquipment_Call {
	return &MockEquipmentService_CreateEquipment_Call{Call: _e.mock.On("CreateEquipment", ctx, equipment)}
}

func (_c *MockEquipmentService_CreateEquipment_Call) Run(run func(ctx context.Context, equipment *entity.Equipment)) *MockEquipmentService_CreateEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Equipment))
	})
	return _c
}

func (_c *MockEquipmentService_CreateEquipment_Call) Return(_a0 error) *MockEquipmentService_CreateEquipment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentService_CreateEquipment_Call) RunAndReturn(run func(context.Context, *entity.Equipment) error) *MockEquipmentService_CreateEquipment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEquipment provides a mock function with given fields: ctx, id
func (_m *MockEquipmentService) DeleteEquipment(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEquipment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentService_DeleteEquipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEquipment'
type MockEquipmentService_DeleteEquipment_Call struct {
	*mock.Call
}

// DeleteEquipment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEquipmentService_Expecter) DeleteEquipment(ctx interface{}, id interface{}) *MockEquipmentService_DeleteEquipment_Call {
	return &MockEquipmentService_DeleteEquipment_Call{Call: _e.mock.On("DeleteEquipment", ctx, id)}
}

func (_c *MockEquipmentService_DeleteEquipment_Call) Run(run func(ctx context.Context, id uint)) *MockEquipmentService_DeleteEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentService_DeleteEquipment_Call) Return(_a0 error) *MockEquipmentService_DeleteEquipment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentService_DeleteEquipment_Call) RunAndReturn(run func(context.Context, uint) error) *MockEquipmentService_DeleteEquipment_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllEquipments provides a mock function with given fields: ctx, limit, offset
func (_m *MockEquipmentService) FindAllEquipments(ctx context.Context, limit int, offset int) ([]entity.Equipment, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllEquipments")
	}

	var r0 []entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.Equipment, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.Equipment); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_FindAllEquipments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllEquipments'
type MockEquipmentService_FindAllEquipments_Call struct {
	*mock.Call
}

// FindAllEquipments is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockEquipmentService_Expecter) FindAllEquipments(ctx interface{}, limit interface{}, offset interface{}) *MockEquipmentService_FindAllEquipments_Call {
	return &MockEquipmentService_FindAllEquipments_Call{Call: _e.mock.On("FindAllEquipments", ctx, limit, offset)}
}

func (_c *MockEquipmentService_FindAllEquipments_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockEquipmentService_FindAllEquipments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockEquipmentService_FindAllEquipments_Call) Return(_a0 []entity.Equipment, _a1 error) *MockEquipmentService_FindAllEquipments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_FindAllEquipments_Call) RunAndReturn(run func(context.Context, int, int) ([]entity.Equipment, error)) *MockEquipmentService_FindAllEquipments_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllEquipmentsWithFilter provides a mock function with given fields: ctx, limit, offset, status, search, expiryFilter, categoryID
func (_m *MockEquipmentService) FindAllEquipmentsWithFilter(ctx context.Context, limit int, offset int, status string, search string, expiryFilter string, categoryID string) ([]entity.Equipment, error) {
	ret := _m.Called(ctx, limit, offset, status, search, expiryFilter, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllEquipmentsWithFilter")
	}

	var r0 []entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) ([]entity.Equipment, error)); ok {
		return rf(ctx, limit, offset, status, search, expiryFilter, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) []entity.Equipment); ok {
		r0 = rf(ctx, limit, offset, status, search, expiryFilter, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string) error); ok {
		r1 = rf(ctx, limit, offset, status, search, expiryFilter, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_FindAllEquipmentsWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllEquipmentsWithFilter'
type MockEquipmentService_FindAllEquipmentsWithFilter_Call struct {
	*mock.Call
}

// FindAllEquipmentsWithFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - status string
//   - search string
//   - expiryFilter string
//   - categoryID string
func (_e *MockEquipmentService_Expecter) FindAllEquipmentsWithFilter(ctx interface{}, limit interface{}, offset interface{}, status interface{}, search interface{}, expiryFilter interface{}, categoryID interface{}) *MockEquipmentService_FindAllEquipmentsWithFilter_Call {
	return &MockEquipmentService_FindAllEquipmentsWithFilter_Call{Call: _e.mock.On("FindAllEquipmentsWithFilter", ctx, limit, offset, status, search, expiryFilter, categoryID)}
}

func (_c *MockEquipmentService_FindAllEquipmentsWithFilter_Call) Run(run func(ctx context.Context, limit int, offset int, status string, search string, expiryFilter string, categoryID string)) *MockEquipmentService_FindAllEquipmentsWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockEquipmentService_FindAllEquipmentsWithFilter_Call) Return(_a0 []entity.Equipment, _a1 error) *MockEquipmentService_FindAllEquipmentsWithFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_FindAllEquipmentsWithFilter_Call) RunAndReturn(run func(context.Context, int, int, string, string, string, string) ([]entity.Equipment, error)) *MockEquipmentService_FindAllEquipmentsWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// FindEquipmentByID provides a mock function with given fields: ctx, id
func (_m *MockEquipmentService) FindEquipmentByID(ctx context.Context, id uint) (*entity.Equipment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindEquipmentByID")
	}

	var r0 *entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Equipment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Equipment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_FindEquipmentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEquipmentByID'
type MockEquipmentService_FindEquipmentByID_Call struct {
	*mock.Call
}

// FindEquipmentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEquipmentService_Expecter) FindEquipmentByID(ctx interface{}, id interface{}) *MockEquipmentService_FindEquipmentByID_Call {
	return &MockEquipmentService_FindEquipmentByID_Call{Call: _e.mock.On("FindEquipmentByID", ctx, id)}
}

func (_c *MockEquipmentService_FindEquipmentByID_Call) Run(run func(ctx context.Context, id uint)) *MockEquipmentService_FindEquipmentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentService_FindEquipmentByID_Call) Return(_a0 *entity.Equipment, _a1 error) *MockEquipmentService_FindEquipmentByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_FindEquipmentByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Equipment, error)) *MockEquipmentService_FindEquipmentByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindEquipmentByIDCode provides a mock function with given fields: ctx, idCode
func (_m *MockEquipmentService) FindEquipmentByIDCode(ctx context.Context, idCode string) (*entity.Equipment, error) {
	ret := _m.Called(ctx, idCode)

	if len(ret) == 0 {
		panic("no return value specified for FindEquipmentByIDCode")
	}

	var r0 *entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Equipment, error)); ok {
		return rf(ctx, idCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Equipment); ok {
		r0 = rf(ctx, idCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_FindEquipmentByIDCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindEquipmentByIDCode'
type MockEquipmentService_FindEquipmentByIDCode_Call struct {
	*mock.Call
}

// FindEquipmentByIDCode is a helper method to define mock.On call
//   - ctx context.Context
//   - idCode string
func (_e *MockEquipmentService_Expecter) FindEquipmentByIDCode(ctx interface{}, idCode interface{}) *MockEquipmentService_FindEquipmentByIDCode_Call {
	return &MockEquipmentService_FindEquipmentByIDCode_Call{Call: _e.mock.On("FindEquipmentByIDCode", ctx, idCode)}
}

func (_c *MockEquipmentService_FindEquipmentByIDCode_Call) Run(run func(ctx context.Context, idCode string)) *MockEquipmentService_FindEquipmentByIDCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEquipmentService_FindEquipmentByIDCode_Call) Return(_a0 *entity.Equipment, _a1 error) *MockEquipmentService_FindEquipmentByIDCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_FindEquipmentByIDCode_Call) RunAndReturn(run func(context.Context, string) (*entity.Equipment, error)) *MockEquipmentService_FindEquipmentByIDCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateBrand provides a mock function with given fields: ctx, brandName
func (_m *MockEquipmentService) FindOrCreateBrand(ctx context.Context, brandName string) (*entity.Brand, error) {
	ret := _m.Called(ctx, brandName)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateBrand")
	}

	var r0 *entity.Brand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Brand, error)); ok {
		return rf(ctx, brandName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Brand); ok {
		r0 = rf(ctx, brandName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, brandName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_FindOrCreateBrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateBrand'
type MockEquipmentService_FindOrCreateBrand_Call struct {
	*mock.Call
}

// FindOrCreateBrand is a helper method to define mock.On call
//   - ctx context.Context
//   - brandName string
func (_e *MockEquipmentService_Expecter) FindOrCreateBrand(ctx interface{}, brandName interface{}) *MockEquipmentService_FindOrCreateBrand_Call {
	return &MockEquipmentService_FindOrCreateBrand_Call{Call: _e.mock.On("FindOrCreateBrand", ctx, brandName)}
}

func (_c *MockEquipmentService_FindOrCreateBrand_Call) Run(run func(ctx context.Context, brandName string)) *MockEquipmentService_FindOrCreateBrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEquipmentService_FindOrCreateBrand_Call) Return(_a0 *entity.Brand, _a1 error) *MockEquipmentService_FindOrCreateBrand_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_FindOrCreateBrand_Call) RunAndReturn(run func(context.Context, string) (*entity.Brand, error)) *MockEquipmentService_FindOrCreateBrand_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateCategory provides a mock function with given fields: ctx, categoryName, riskLevel, description
func (_m *MockEquipmentService) FindOrCreateCategory(ctx context.Context, categoryName string, riskLevel entity.ECRIRiskLevel, description string) (*entity.EquipmentCategory, error) {
	ret := _m.Called(ctx, categoryName, riskLevel, description)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateCategory")
	}

	var r0 *entity.EquipmentCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.ECRIRiskLevel, string) (*entity.EquipmentCategory, error)); ok {
		return rf(ctx, categoryName, riskLevel, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, entity.ECRIRiskLevel, string) *entity.EquipmentCategory); ok {
		r0 = rf(ctx, categoryName, riskLevel, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EquipmentCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, entity.ECRIRiskLevel, string) error); ok {
		r1 = rf(ctx, categoryName, riskLevel, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_FindOrCreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateCategory'
type MockEquipmentService_FindOrCreateCategory_Call struct {
	*mock.Call
}

// FindOrCreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryName string
//   - riskLevel entity.ECRIRiskLevel
//   - description string
func (_e *MockEquipmentService_Expecter) FindOrCreateCategory(ctx interface{}, categoryName interface{}, riskLevel interface{}, description interface{}) *MockEquipmentService_FindOrCreateCategory_Call {
	return &MockEquipmentService_FindOrCreateCategory_Call{Call: _e.mock.On("FindOrCreateCategory", ctx, categoryName, riskLevel, description)}
}

func (_c *MockEquipmentService_FindOrCreateCategory_Call) Run(run func(ctx context.Context, categoryName string, riskLevel entity.ECRIRiskLevel, description string)) *MockEquipmentService_FindOrCreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entity.ECRIRiskLevel), args[3].(string))
	})
	return _c
}

func (_c *MockEquipmentService_FindOrCreateCategory_Call) Return(_a0 *entity.EquipmentCategory, _a1 error) *MockEquipmentService_FindOrCreateCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_FindOrCreateCategory_Call) RunAndReturn(run func(context.Context, string, entity.ECRIRiskLevel, string) (*entity.EquipmentCategory, error)) *MockEquipmentService_FindOrCreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateDepartment provides a mock function with given fields: ctx, departmentName
func (_m *MockEquipmentService) FindOrCreateDepartment(ctx context.Context, departmentName string) (*entity.Department, error) {
	ret := _m.Called(ctx, departmentName)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateDepartment")
	}

	var r0 *entity.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Department, error)); ok {
		return rf(ctx, departmentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Department); ok {
		r0 = rf(ctx, departmentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, departmentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_FindOrCreateDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateDepartment'
type MockEquipmentService_FindOrCreateDepartment_Call struct {
	*mock.Call
}

// FindOrCreateDepartment is a helper method to define mock.On call
//   - ctx context.Context
//   - departmentName string
func (_e *MockEquipmentService_Expecter) FindOrCreateDepartment(ctx interface{}, departmentName interface{}) *MockEquipmentService_FindOrCreateDepartment_Call {
	return &MockEquipmentService_FindOrCreateDepartment_Call{Call: _e.mock.On("FindOrCreateDepartment", ctx, departmentName)}
}

func (_c *MockEquipmentService_FindOrCreateDepartment_Call) Run(run func(ctx context.Context, departmentName string)) *MockEquipmentService_FindOrCreateDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEquipmentService_FindOrCreateDepartment_Call) Return(_a0 *entity.Department, _a1 error) *MockEquipmentService_FindOrCreateDepartment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_FindOrCreateDepartment_Call) RunAndReturn(run func(context.Context, string) (*entity.Department, error)) *MockEquipmentService_FindOrCreateDepartment_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateModel provides a mock function with given fields: ctx, modelName, brandID, categoryID, lifeExpectancy
func (_m *MockEquipmentService) FindOrCreateModel(ctx context.Context, modelName string, brandID uint, categoryID uint, lifeExpectancy float64) (*entity.EquipmentModel, error) {
	ret := _m.Called(ctx, modelName, brandID, categoryID, lifeExpectancy)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateModel")
	}

	var r0 *entity.EquipmentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, float64) (*entity.EquipmentModel, error)); ok {
		return rf(ctx, modelName, brandID, categoryID, lifeExpectancy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, float64) *entity.EquipmentModel); ok {
		r0 = rf(ctx, modelName, brandID, categoryID, lifeExpectancy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EquipmentModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint, float64) error); ok {
		r1 = rf(ctx, modelName, brandID, categoryID, lifeExpectancy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_FindOrCreateModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateModel'
type MockEquipmentService_FindOrCreateModel_Call struct {
	*mock.Call
}

// FindOrCreateModel is a helper method to define mock.On call
//   - ctx context.Context
//   - modelName string
//   - brandID uint
//   - categoryID uint
//   - lifeExpectancy float64
func (_e *MockEquipmentService_Expecter) FindOrCreateModel(ctx interface{}, modelName interface{}, brandID interface{}, categoryID interface{}, lifeExpectancy interface{}) *MockEquipmentService_FindOrCreateModel_Call {
	return &MockEquipmentService_FindOrCreateModel_Call{Call: _e.mock.On("FindOrCreateModel", ctx, modelName, brandID, categoryID, lifeExpectancy)}
}

func (_c *MockEquipmentService_FindOrCreateModel_Call) Run(run func(ctx context.Context, modelName string, brandID uint, categoryID uint, lifeExpectancy float64)) *MockEquipmentService_FindOrCreateModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint), args[3].(uint), args[4].(float64))
	})
	return _c
}

func (_c *MockEquipmentService_FindOrCreateModel_Call) Return(_a0 *entity.EquipmentModel, _a1 error) *MockEquipmentService_FindOrCreateModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_FindOrCreateModel_Call) RunAndReturn(run func(context.Context, string, uint, uint, float64) (*entity.EquipmentModel, error)) *MockEquipmentService_FindOrCreateModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCategories provides a mock function with given fields: ctx
func (_m *MockEquipmentService) GetAllCategories(ctx context.Context) ([]entity.EquipmentCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []entity.EquipmentCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.EquipmentCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.EquipmentCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EquipmentCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentService_GetAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCategories'
type MockEquipmentService_GetAllCategories_Call struct {
	*mock.Call
}

// GetAllCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentService_Expecter) GetAllCategories(ctx interface{}) *MockEquipmentService_GetAllCategories_Call {
	return &MockEquipmentService_GetAllCategories_Call{Call: _e.mock.On("GetAllCategories", ctx)}
}

func (_c *MockEquipmentService_GetAllCategories_Call) Run(run func(ctx context.Context)) *MockEquipmentService_GetAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEquipmentService_GetAllCategories_Call) Return(_a0 []entity.EquipmentCategory, _a1 error) *MockEquipmentService_GetAllCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentService_GetAllCategories_Call) RunAndReturn(run func(context.Context) ([]entity.EquipmentCategory, error)) *MockEquipmentService_GetAllCategories_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEquipment provides a mock function with given fields: ctx, equipment
func (_m *MockEquipmentService) UpdateEquipment(ctx context.Context, equipment *entity.Equipment) error {
	ret := _m.Called(ctx, equipment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEquipment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Equipment) error); ok {
		r0 = rf(ctx, equipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentService_UpdateEquipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEquipment'
type MockEquipmentService_UpdateEquipment_Call struct {
	*mock.Call
}

// UpdateEquipment is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment *entity.Equipment
func (_e *MockEquipmentService_Expecter) UpdateEquipment(ctx interface{}, equipment interface{}) *MockEquipmentService_UpdateEquipment_Call {
	return &MockEquipmentService_UpdateEquipment_Call{Call: _e.mock.On("UpdateEquipment", ctx, equipment)}
}

func (_c *MockEquipmentService_UpdateEquipment_Call) Run(run func(ctx context.Context, equipment *entity.Equipment)) *MockEquipmentService_UpdateEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Equipment))
	})
	return _c
}

func (_c *MockEquipmentService_UpdateEquipment_Call) Return(_a0 error) *MockEquipmentService_UpdateEquipment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentService_UpdateEquipment_Call) RunAndReturn(run func(context.Context, *entity.Equipment) error) *MockEquipmentService_UpdateEquipment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEquipmentService creates a new instance of MockEquipmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEquipmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEquipmentService {
	mock := &MockEquipmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
