with-expecter: true
dir: "internal/mocks/{{.PackageName}}"
outpkg: "mock_{{.PackageName}}"
packages:
  medical-webhook/internal/domain/line/repository:
    interfaces:
      EquipmentRepository:
      TicketRepository:
      DepartmentRepository:
      BrandRepository:
      EquipmentCategoryRepository:
      EquipmentModelRepository:
  medical-webhook/internal/application/service:
    interfaces:
      EquipmentService:
  medical-webhook/internal/domain/event:
    interfaces:
      EventBus:
