// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repository

import (
	context "context"
	entity "medical-webhook/internal/domain/line/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockDepartmentRepository is an autogenerated mock type for the DepartmentRepository type
type MockDepartmentRepository struct {
	mock.Mock
}

type MockDepartmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDepartmentRepository) EXPECT() *MockDepartmentRepository_Expecter {
	return &MockDepartmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, department
func (_m *MockDepartmentRepository) Create(ctx context.Context, department *entity.Department) error {
	ret := _m.Called(ctx, department)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Department) error); ok {
		r0 = rf(ctx, department)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDepartmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDepartmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - department *entity.Department
func (_e *MockDepartmentRepository_Expecter) Create(ctx interface{}, department interface{}) *MockDepartmentRepository_Create_Call {
	return &MockDepartmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, department)}
}

func (_c *MockDepartmentRepository_Create_Call) Run(run func(ctx context.Context, department *entity.Department)) *MockDepartmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Department))
	})
	return _c
}

func (_c *MockDepartmentRepository_Create_Call) Return(_a0 error) *MockDepartmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepartmentRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Department) error) *MockDepartmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockDepartmentRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDepartmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDepartmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockDepartmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockDepartmentRepository_Delete_Call {
	return &MockDepartmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDepartmentRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockDepartmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockDepartmentRepository_Delete_Call) Return(_a0 error) *MockDepartmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepartmentRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockDepartmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockDepartmentRepository) FindAll(ctx context.Context) ([]entity.Department, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Department, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Department); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepartmentRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockDepartmentRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDepartmentRepository_Expecter) FindAll(ctx interface{}) *MockDepartmentRepository_FindAll_Call {
	return &MockDepartmentRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockDepartmentRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockDepartmentRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDepartmentRepository_FindAll_Call) Return(_a0 []entity.Department, _a1 error) *MockDepartmentRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepartmentRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.Department, error)) *MockDepartmentRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockDepartmentRepository) FindByID(ctx context.Context, id uint) (*entity.Department, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Department, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Department); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepartmentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockDepartmentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockDepartmentRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockDepartmentRepository_FindByID_Call {
	return &MockDepartmentRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockDepartmentRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockDepartmentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockDepartmentRepository_FindByID_Call) Return(_a0 *entity.Department, _a1 error) *MockDepartmentRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepartmentRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Department, error)) *MockDepartmentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockDepartmentRepository) FindByName(ctx context.Context, name string) (*entity.Department, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Department, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Department); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepartmentRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockDepartmentRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDepartmentRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockDepartmentRepository_FindByName_Call {
	return &MockDepartmentRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockDepartmentRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockDepartmentRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDepartmentRepository_FindByName_Call) Return(_a0 *entity.Department, _a1 error) *MockDepartmentRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepartmentRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*entity.Department, error)) *MockDepartmentRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreate provides a mock function with given fields: ctx, name
func (_m *MockDepartmentRepository) FindOrCreate(ctx context.Context, name string) (*entity.Department, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *entity.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Department, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Department); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepartmentRepository_FindOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreate'
type MockDepartmentRepository_FindOrCreate_Call struct {
	*mock.Call
}

// FindOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDepartmentRepository_Expecter) FindOrCreate(ctx interface{}, name interface{}) *MockDepartmentRepository_FindOrCreate_Call {
	return &MockDepartmentRepository_FindOrCreate_Call{Call: _e.mock.On("FindOrCreate", ctx, name)}
}

func (_c *MockDepartmentRepository_FindOrCreate_Call) Run(run func(ctx context.Context, name string)) *MockDepartmentRepository_FindOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDepartmentRepository_FindOrCreate_Call) Return(_a0 *entity.Department, _a1 error) *MockDepartmentRepository_FindOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepartmentRepository_FindOrCreate_Call) RunAndReturn(run func(context.Context, string) (*entity.Department, error)) *MockDepartmentRepository_FindOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByNameLike provides a mock function with given fields: ctx, keyword, limit
func (_m *MockDepartmentRepository) SearchByNameLike(ctx context.Context, keyword string, limit int) ([]entity.Department, error) {
	ret := _m.Called(ctx, keyword, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchByNameLike")
	}

	var r0 []entity.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]entity.Department, error)); ok {
		return rf(ctx, keyword, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []entity.Department); ok {
		r0 = rf(ctx, keyword, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, keyword, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDepartmentRepository_SearchByNameLike_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByNameLike'
type MockDepartmentRepository_SearchByNameLike_Call struct {
	*mock.Call
}

// SearchByNameLike is a helper method to define mock.On call
//   - ctx context.Context
//   - keyword string
//   - limit int
func (_e *MockDepartmentRepository_Expecter) SearchByNameLike(ctx interface{}, keyword interface{}, limit interface{}) *MockDepartmentRepository_SearchByNameLike_Call {
	return &MockDepartmentRepository_SearchByNameLike_Call{Call: _e.mock.On("SearchByNameLike", ctx, keyword, limit)}
}

func (_c *MockDepartmentRepository_SearchByNameLike_Call) Run(run func(ctx context.Context, keyword string, limit int)) *MockDepartmentRepository_SearchByNameLike_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockDepartmentRepository_SearchByNameLike_Call) Return(_a0 []entity.Department, _a1 error) *MockDepartmentRepository_SearchByNameLike_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDepartmentRepository_SearchByNameLike_Call) RunAndReturn(run func(context.Context, string, int) ([]entity.Department, error)) *MockDepartmentRepository_SearchByNameLike_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, department
func (_m *MockDepartmentRepository) Update(ctx context.Context, department *entity.Department) error {
	ret := _m.Called(ctx, department)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Department) error); ok {
		r0 = rf(ctx, department)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDepartmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDepartmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - department *entity.Department
func (_e *MockDepartmentRepository_Expecter) Update(ctx interface{}, department interface{}) *MockDepartmentRepository_Update_Call {
	return &MockDepartmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, department)}
}

func (_c *MockDepartmentRepository_Update_Call) Run(run func(ctx context.Context, department *entity.Department)) *MockDepartmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Department))
	})
	return _c
}

func (_c *MockDepartmentRepository_Update_Call) Return(_a0 error) *MockDepartmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDepartmentRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Department) error) *MockDepartmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDepartmentRepository creates a new instance of MockDepartmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDepartmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDepartmentRepository {
	mock := &MockDepartmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
