// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repository

import (
	context "context"
	entity "medical-webhook/internal/domain/line/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockEquipmentRepository is an autogenerated mock type for the EquipmentRepository type
type MockEquipmentRepository struct {
	mock.Mock
}

type MockEquipmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEquipmentRepository) EXPECT() *MockEquipmentRepository_Expecter {
	return &MockEquipmentRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx
func (_m *MockEquipmentRepository) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockEquipmentRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentRepository_Expecter) Count(ctx interface{}) *MockEquipmentRepository_Count_Call {
	return &MockEquipmentRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockEquipmentRepository_Count_Call) Run(run func(ctx context.Context)) *MockEquipmentRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEquipmentRepository_Count_Call) Return(_a0 int64, _a1 error) *MockEquipmentRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_Count_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockEquipmentRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByStatus provides a mock function with given fields: ctx
func (_m *MockEquipmentRepository) CountByStatus(ctx context.Context) (map[entity.AssetStatus]int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 map[entity.AssetStatus]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[entity.AssetStatus]int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[entity.AssetStatus]int64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[entity.AssetStatus]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockEquipmentRepository_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentRepository_Expecter) CountByStatus(ctx interface{}) *MockEquipmentRepository_CountByStatus_Call {
	return &MockEquipmentRepository_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx)}
}

func (_c *MockEquipmentRepository_CountByStatus_Call) Run(run func(ctx context.Context)) *MockEquipmentRepository_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEquipmentRepository_CountByStatus_Call) Return(_a0 map[entity.AssetStatus]int64, _a1 error) *MockEquipmentRepository_CountByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_CountByStatus_Call) RunAndReturn(run func(context.Context) (map[entity.AssetStatus]int64, error)) *MockEquipmentRepository_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CountExpired provides a mock function with given fields: ctx
func (_m *MockEquipmentRepository) CountExpired(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountExpired")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_CountExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountExpired'
type MockEquipmentRepository_CountExpired_Call struct {
	*mock.Call
}

// CountExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentRepository_Expecter) CountExpired(ctx interface{}) *MockEquipmentRepository_CountExpired_Call {
	return &MockEquipmentRepository_CountExpired_Call{Call: _e.mock.On("CountExpired", ctx)}
}

func (_c *MockEquipmentRepository_CountExpired_Call) Run(run func(ctx context.Context)) *MockEquipmentRepository_CountExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEquipmentRepository_CountExpired_Call) Return(_a0 int64, _a1 error) *MockEquipmentRepository_CountExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_CountExpired_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockEquipmentRepository_CountExpired_Call {
	_c.Call.Return(run)
	return _c
}

// CountNearExpiry provides a mock function with given fields: ctx
func (_m *MockEquipmentRepository) CountNearExpiry(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountNearExpiry")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_CountNearExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountNearExpiry'
type MockEquipmentRepository_CountNearExpiry_Call struct {
	*mock.Call
}

// CountNearExpiry is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentRepository_Expecter) CountNearExpiry(ctx interface{}) *MockEquipmentRepository_CountNearExpiry_Call {
	return &MockEquipmentRepository_CountNearExpiry_Call{Call: _e.mock.On("CountNearExpiry", ctx)}
}

func (_c *MockEquipmentRepository_CountNearExpiry_Call) Run(run func(ctx context.Context)) *MockEquipmentRepository_CountNearExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEquipmentRepository_CountNearExpiry_Call) Return(_a0 int64, _a1 error) *MockEquipmentRepository_CountNearExpiry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_CountNearExpiry_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockEquipmentRepository_CountNearExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// CountWithFilter provides a mock function with given fields: ctx, status, search, expiryFilter, categoryID
func (_m *MockEquipmentRepository) CountWithFilter(ctx context.Context, status string, search string, expiryFilter string, categoryID string) (int64, error) {
	ret := _m.Called(ctx, status, search, expiryFilter, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for CountWithFilter")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (int64, error)); ok {
		return rf(ctx, status, search, expiryFilter, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) int64); ok {
		r0 = rf(ctx, status, search, expiryFilter, categoryID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, status, search, expiryFilter, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_CountWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountWithFilter'
type MockEquipmentRepository_CountWithFilter_Call struct {
	*mock.Call
}

// CountWithFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - search string
//   - expiryFilter string
//   - categoryID string
func (_e *MockEquipmentRepository_Expecter) CountWithFilter(ctx interface{}, status interface{}, search interface{}, expiryFilter interface{}, categoryID interface{}) *MockEquipmentRepository_CountWithFilter_Call {
	return &MockEquipmentRepository_CountWithFilter_Call{Call: _e.mock.On("CountWithFilter", ctx, status, search, expiryFilter, categoryID)}
}

func (_c *MockEquipmentRepository_CountWithFilter_Call) Run(run func(ctx context.Context, status string, search string, expiryFilter string, categoryID string)) *MockEquipmentRepository_CountWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockEquipmentRepository_CountWithFilter_Call) Return(_a0 int64, _a1 error) *MockEquipmentRepository_CountWithFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_CountWithFilter_Call) RunAndReturn(run func(context.Context, string, string, string, string) (int64, error)) *MockEquipmentRepository_CountWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, equipment
func (_m *MockEquipmentRepository) Create(ctx context.Context, equipment *entity.Equipment) error {
	ret := _m.Called(ctx, equipment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Equipment) error); ok {
		r0 = rf(ctx, equipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEquipmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment *entity.Equipment
func (_e *MockEquipmentRepository_Expecter) Create(ctx interface{}, equipment interface{}) *MockEquipmentRepository_Create_Call {
	return &MockEquipmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, equipment)}
}

func (_c *MockEquipmentRepository_Create_Call) Run(run func(ctx context.Context, equipment *entity.Equipment)) *MockEquipmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Equipment))
	})
	return _c
}

func (_c *MockEquipmentRepository_Create_Call) Return(_a0 error) *MockEquipmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Equipment) error) *MockEquipmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMaintenanceRecord provides a mock function with given fields: record
func (_m *MockEquipmentRepository) CreateMaintenanceRecord(record *entity.MaintenanceRecord) error {
	ret := _m.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for CreateMaintenanceRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.MaintenanceRecord) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentRepository_CreateMaintenanceRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMaintenanceRecord'
type MockEquipmentRepository_CreateMaintenanceRecord_Call struct {
	*mock.Call
}

// CreateMaintenanceRecord is a helper method to define mock.On call
//   - record *entity.MaintenanceRecord
func (_e *MockEquipmentRepository_Expecter) CreateMaintenanceRecord(record interface{}) *MockEquipmentRepository_CreateMaintenanceRecord_Call {
	return &MockEquipmentRepository_CreateMaintenanceRecord_Call{Call: _e.mock.On("CreateMaintenanceRecord", record)}
}

func (_c *MockEquipmentRepository_CreateMaintenanceRecord_Call) Run(run func(record *entity.MaintenanceRecord)) *MockEquipmentRepository_CreateMaintenanceRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.MaintenanceRecord))
	})
	return _c
}

func (_c *MockEquipmentRepository_CreateMaintenanceRecord_Call) Return(_a0 error) *MockEquipmentRepository_CreateMaintenanceRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentRepository_CreateMaintenanceRecord_Call) RunAndReturn(run func(*entity.MaintenanceRecord) error) *MockEquipmentRepository_CreateMaintenanceRecord_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdate provides a mock function with given fields: ctx, equipment
func (_m *MockEquipmentRepository) CreateOrUpdate(ctx context.Context, equipment *entity.Equipment) (bool, error) {
	ret := _m.Called(ctx, equipment)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Equipment) (bool, error)); ok {
		return rf(ctx, equipment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Equipment) bool); ok {
		r0 = rf(ctx, equipment)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Equipment) error); ok {
		r1 = rf(ctx, equipment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type MockEquipmentRepository_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment *entity.Equipment
func (_e *MockEquipmentRepository_Expecter) CreateOrUpdate(ctx interface{}, equipment interface{}) *MockEquipmentRepository_CreateOrUpdate_Call {
	return &MockEquipmentRepository_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate", ctx, equipment)}
}

func (_c *MockEquipmentRepository_CreateOrUpdate_Call) Run(run func(ctx context.Context, equipment *entity.Equipment)) *MockEquipmentRepository_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Equipment))
	})
	return _c
}

func (_c *MockEquipmentRepository_CreateOrUpdate_Call) Return(_a0 bool, _a1 error) *MockEquipmentRepository_CreateOrUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_CreateOrUpdate_Call) RunAndReturn(run func(context.Context, *entity.Equipment) (bool, error)) *MockEquipmentRepository_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockEquipmentRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEquipmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEquipmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockEquipmentRepository_Delete_Call {
	return &MockEquipmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEquipmentRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockEquipmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentRepository_Delete_Call) Return(_a0 error) *MockEquipmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockEquipmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, limit, offset
func (_m *MockEquipmentRepository) FindAll(ctx context.Context, limit int, offset int) ([]entity.Equipment, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.Equipment, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.Equipment); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockEquipmentRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockEquipmentRepository_Expecter) FindAll(ctx interface{}, limit interface{}, offset interface{}) *MockEquipmentRepository_FindAll_Call {
	return &MockEquipmentRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, limit, offset)}
}

func (_c *MockEquipmentRepository_FindAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockEquipmentRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindAll_Call) Return(_a0 []entity.Equipment, _a1 error) *MockEquipmentRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]entity.Equipment, error)) *MockEquipmentRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllWithFilter provides a mock function with given fields: ctx, limit, offset, status, search, expiryFilter, categoryID
func (_m *MockEquipmentRepository) FindAllWithFilter(ctx context.Context, limit int, offset int, status string, search string, expiryFilter string, categoryID string) ([]entity.Equipment, error) {
	ret := _m.Called(ctx, limit, offset, status, search, expiryFilter, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithFilter")
	}

	var r0 []entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) ([]entity.Equipment, error)); ok {
		return rf(ctx, limit, offset, status, search, expiryFilter, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) []entity.Equipment); ok {
		r0 = rf(ctx, limit, offset, status, search, expiryFilter, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string) error); ok {
		r1 = rf(ctx, limit, offset, status, search, expiryFilter, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindAllWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithFilter'
type MockEquipmentRepository_FindAllWithFilter_Call struct {
	*mock.Call
}

// FindAllWithFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - status string
//   - search string
//   - expiryFilter string
//   - categoryID string
func (_e *MockEquipmentRepository_Expecter) FindAllWithFilter(ctx interface{}, limit interface{}, offset interface{}, status interface{}, search interface{}, expiryFilter interface{}, categoryID interface{}) *MockEquipmentRepository_FindAllWithFilter_Call {
	return &MockEquipmentRepository_FindAllWithFilter_Call{Call: _e.mock.On("FindAllWithFilter", ctx, limit, offset, status, search, expiryFilter, categoryID)}
}

func (_c *MockEquipmentRepository_FindAllWithFilter_Call) Run(run func(ctx context.Context, limit int, offset int, status string, search string, expiryFilter string, categoryID string)) *MockEquipmentRepository_FindAllWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindAllWithFilter_Call) Return(_a0 []entity.Equipment, _a1 error) *MockEquipmentRepository_FindAllWithFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindAllWithFilter_Call) RunAndReturn(run func(context.Context, int, int, string, string, string, string) ([]entity.Equipment, error)) *MockEquipmentRepository_FindAllWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// FindBestMatch provides a mock function with given fields: query
func (_m *MockEquipmentRepository) FindBestMatch(query string) (*entity.Equipment, int, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for FindBestMatch")
	}

	var r0 *entity.Equipment
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Equipment, int, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Equipment); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) int); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockEquipmentRepository_FindBestMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBestMatch'
type MockEquipmentRepository_FindBestMatch_Call struct {
	*mock.Call
}

// FindBestMatch is a helper method to define mock.On call
//   - query string
func (_e *MockEquipmentRepository_Expecter) FindBestMatch(query interface{}) *MockEquipmentRepository_FindBestMatch_Call {
	return &MockEquipmentRepository_FindBestMatch_Call{Call: _e.mock.On("FindBestMatch", query)}
}

func (_c *MockEquipmentRepository_FindBestMatch_Call) Run(run func(query string)) *MockEquipmentRepository_FindBestMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindBestMatch_Call) Return(_a0 *entity.Equipment, _a1 int, _a2 error) *MockEquipmentRepository_FindBestMatch_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockEquipmentRepository_FindBestMatch_Call) RunAndReturn(run func(string) (*entity.Equipment, int, error)) *MockEquipmentRepository_FindBestMatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockEquipmentRepository) FindByID(ctx context.Context, id uint) (*entity.Equipment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Equipment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Equipment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockEquipmentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEquipmentRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockEquipmentRepository_FindByID_Call {
	return &MockEquipmentRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockEquipmentRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockEquipmentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindByID_Call) Return(_a0 *entity.Equipment, _a1 error) *MockEquipmentRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Equipment, error)) *MockEquipmentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDCode provides a mock function with given fields: idCode
func (_m *MockEquipmentRepository) FindByIDCode(idCode string) (*entity.Equipment, error) {
	ret := _m.Called(idCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDCode")
	}

	var r0 *entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Equipment, error)); ok {
		return rf(idCode)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Equipment); ok {
		r0 = rf(idCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(idCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindByIDCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDCode'
type MockEquipmentRepository_FindByIDCode_Call struct {
	*mock.Call
}

// FindByIDCode is a helper method to define mock.On call
//   - idCode string
func (_e *MockEquipmentRepository_Expecter) FindByIDCode(idCode interface{}) *MockEquipmentRepository_FindByIDCode_Call {
	return &MockEquipmentRepository_FindByIDCode_Call{Call: _e.mock.On("FindByIDCode", idCode)}
}

func (_c *MockEquipmentRepository_FindByIDCode_Call) Run(run func(idCode string)) *MockEquipmentRepository_FindByIDCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindByIDCode_Call) Return(_a0 *entity.Equipment, _a1 error) *MockEquipmentRepository_FindByIDCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindByIDCode_Call) RunAndReturn(run func(string) (*entity.Equipment, error)) *MockEquipmentRepository_FindByIDCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByReplacementYear provides a mock function with given fields: ctx, year, departmentID
func (_m *MockEquipmentRepository) FindByReplacementYear(ctx context.Context, year int, departmentID *uint) ([]entity.Equipment, error) {
	ret := _m.Called(ctx, year, departmentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByReplacementYear")
	}

	var r0 []entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *uint) ([]entity.Equipment, error)); ok {
		return rf(ctx, year, departmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *uint) []entity.Equipment); ok {
		r0 = rf(ctx, year, departmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *uint) error); ok {
		r1 = rf(ctx, year, departmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindByReplacementYear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByReplacementYear'
type MockEquipmentRepository_FindByReplacementYear_Call struct {
	*mock.Call
}

// FindByReplacementYear is a helper method to define mock.On call
//   - ctx context.Context
//   - year int
//   - departmentID *uint
func (_e *MockEquipmentRepository_Expecter) FindByReplacementYear(ctx interface{}, year interface{}, departmentID interface{}) *MockEquipmentRepository_FindByReplacementYear_Call {
	return &MockEquipmentRepository_FindByReplacementYear_Call{Call: _e.mock.On("FindByReplacementYear", ctx, year, departmentID)}
}

func (_c *MockEquipmentRepository_FindByReplacementYear_Call) Run(run func(ctx context.Context, year int, departmentID *uint)) *MockEquipmentRepository_FindByReplacementYear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*uint))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindByReplacementYear_Call) Return(_a0 []entity.Equipment, _a1 error) *MockEquipmentRepository_FindByReplacementYear_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindByReplacementYear_Call) RunAndReturn(run func(context.Context, int, *uint) ([]entity.Equipment, error)) *MockEquipmentRepository_FindByReplacementYear_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySerialNo provides a mock function with given fields: serialNo
func (_m *MockEquipmentRepository) FindBySerialNo(serialNo string) (*entity.Equipment, error) {
	ret := _m.Called(serialNo)

	if len(ret) == 0 {
		panic("no return value specified for FindBySerialNo")
	}

	var r0 *entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Equipment, error)); ok {
		return rf(serialNo)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Equipment); ok {
		r0 = rf(serialNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serialNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindBySerialNo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySerialNo'
type MockEquipmentRepository_FindBySerialNo_Call struct {
	*mock.Call
}

// FindBySerialNo is a helper method to define mock.On call
//   - serialNo string
func (_e *MockEquipmentRepository_Expecter) FindBySerialNo(serialNo interface{}) *MockEquipmentRepository_FindBySerialNo_Call {
	return &MockEquipmentRepository_FindBySerialNo_Call{Call: _e.mock.On("FindBySerialNo", serialNo)}
}

func (_c *MockEquipmentRepository_FindBySerialNo_Call) Run(run func(serialNo string)) *MockEquipmentRepository_FindBySerialNo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindBySerialNo_Call) Return(_a0 *entity.Equipment, _a1 error) *MockEquipmentRepository_FindBySerialNo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindBySerialNo_Call) RunAndReturn(run func(string) (*entity.Equipment, error)) *MockEquipmentRepository_FindBySerialNo_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySerialOrCode provides a mock function with given fields: query
func (_m *MockEquipmentRepository) FindBySerialOrCode(query string) (*entity.Equipment, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for FindBySerialOrCode")
	}

	var r0 *entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Equipment, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Equipment); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindBySerialOrCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySerialOrCode'
type MockEquipmentRepository_FindBySerialOrCode_Call struct {
	*mock.Call
}

// FindBySerialOrCode is a helper method to define mock.On call
//   - query string
func (_e *MockEquipmentRepository_Expecter) FindBySerialOrCode(query interface{}) *MockEquipmentRepository_FindBySerialOrCode_Call {
	return &MockEquipmentRepository_FindBySerialOrCode_Call{Call: _e.mock.On("FindBySerialOrCode", query)}
}

func (_c *MockEquipmentRepository_FindBySerialOrCode_Call) Run(run func(query string)) *MockEquipmentRepository_FindBySerialOrCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindBySerialOrCode_Call) Return(_a0 *entity.Equipment, _a1 error) *MockEquipmentRepository_FindBySerialOrCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindBySerialOrCode_Call) RunAndReturn(run func(string) (*entity.Equipment, error)) *MockEquipmentRepository_FindBySerialOrCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindSimilarByIDCodePrefix provides a mock function with given fields: prefix, limit
func (_m *MockEquipmentRepository) FindSimilarByIDCodePrefix(prefix string, limit int) ([]*entity.Equipment, error) {
	ret := _m.Called(prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindSimilarByIDCodePrefix")
	}

	var r0 []*entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]*entity.Equipment, error)); ok {
		return rf(prefix, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []*entity.Equipment); ok {
		r0 = rf(prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(prefix, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindSimilarByIDCodePrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSimilarByIDCodePrefix'
type MockEquipmentRepository_FindSimilarByIDCodePrefix_Call struct {
	*mock.Call
}

// FindSimilarByIDCodePrefix is a helper method to define mock.On call
//   - prefix string
//   - limit int
func (_e *MockEquipmentRepository_Expecter) FindSimilarByIDCodePrefix(prefix interface{}, limit interface{}) *MockEquipmentRepository_FindSimilarByIDCodePrefix_Call {
	return &MockEquipmentRepository_FindSimilarByIDCodePrefix_Call{Call: _e.mock.On("FindSimilarByIDCodePrefix", prefix, limit)}
}

func (_c *MockEquipmentRepository_FindSimilarByIDCodePrefix_Call) Run(run func(prefix string, limit int)) *MockEquipmentRepository_FindSimilarByIDCodePrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindSimilarByIDCodePrefix_Call) Return(_a0 []*entity.Equipment, _a1 error) *MockEquipmentRepository_FindSimilarByIDCodePrefix_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindSimilarByIDCodePrefix_Call) RunAndReturn(run func(string, int) ([]*entity.Equipment, error)) *MockEquipmentRepository_FindSimilarByIDCodePrefix_Call {
	_c.Call.Return(run)
	return _c
}

// FindSimilarSorted provides a mock function with given fields: query, limit
func (_m *MockEquipmentRepository) FindSimilarSorted(query string, limit int) ([]*entity.Equipment, error) {
	ret := _m.Called(query, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindSimilarSorted")
	}

	var r0 []*entity.Equipment
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]*entity.Equipment, error)); ok {
		return rf(query, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []*entity.Equipment); ok {
		r0 = rf(query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Equipment)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_FindSimilarSorted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSimilarSorted'
type MockEquipmentRepository_FindSimilarSorted_Call struct {
	*mock.Call
}

// FindSimilarSorted is a helper method to define mock.On call
//   - query string
//   - limit int
func (_e *MockEquipmentRepository_Expecter) FindSimilarSorted(query interface{}, limit interface{}) *MockEquipmentRepository_FindSimilarSorted_Call {
	return &MockEquipmentRepository_FindSimilarSorted_Call{Call: _e.mock.On("FindSimilarSorted", query, limit)}
}

func (_c *MockEquipmentRepository_FindSimilarSorted_Call) Run(run func(query string, limit int)) *MockEquipmentRepository_FindSimilarSorted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockEquipmentRepository_FindSimilarSorted_Call) Return(_a0 []*entity.Equipment, _a1 error) *MockEquipmentRepository_FindSimilarSorted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_FindSimilarSorted_Call) RunAndReturn(run func(string, int) ([]*entity.Equipment, error)) *MockEquipmentRepository_FindSimilarSorted_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaintenanceRecords provides a mock function with given fields: equipmentID
func (_m *MockEquipmentRepository) GetMaintenanceRecords(equipmentID uint) ([]entity.MaintenanceRecord, error) {
	ret := _m.Called(equipmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetMaintenanceRecords")
	}

	var r0 []entity.MaintenanceRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]entity.MaintenanceRecord, error)); ok {
		return rf(equipmentID)
	}
	if rf, ok := ret.Get(0).(func(uint) []entity.MaintenanceRecord); ok {
		r0 = rf(equipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.MaintenanceRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(equipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentRepository_GetMaintenanceRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaintenanceRecords'
type MockEquipmentRepository_GetMaintenanceRecords_Call struct {
	*mock.Call
}

// GetMaintenanceRecords is a helper method to define mock.On call
//   - equipmentID uint
func (_e *MockEquipmentRepository_Expecter) GetMaintenanceRecords(equipmentID interface{}) *MockEquipmentRepository_GetMaintenanceRecords_Call {
	return &MockEquipmentRepository_GetMaintenanceRecords_Call{Call: _e.mock.On("GetMaintenanceRecords", equipmentID)}
}

func (_c *MockEquipmentRepository_GetMaintenanceRecords_Call) Run(run func(equipmentID uint)) *MockEquipmentRepository_GetMaintenanceRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockEquipmentRepository_GetMaintenanceRecords_Call) Return(_a0 []entity.MaintenanceRecord, _a1 error) *MockEquipmentRepository_GetMaintenanceRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentRepository_GetMaintenanceRecords_Call) RunAndReturn(run func(uint) ([]entity.MaintenanceRecord, error)) *MockEquipmentRepository_GetMaintenanceRecords_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, equipment
func (_m *MockEquipmentRepository) Update(ctx context.Context, equipment *entity.Equipment) error {
	ret := _m.Called(ctx, equipment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Equipment) error); ok {
		r0 = rf(ctx, equipment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEquipmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment *entity.Equipment
func (_e *MockEquipmentRepository_Expecter) Update(ctx interface{}, equipment interface{}) *MockEquipmentRepository_Update_Call {
	return &MockEquipmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, equipment)}
}

func (_c *MockEquipmentRepository_Update_Call) Run(run func(ctx context.Context, equipment *entity.Equipment)) *MockEquipmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Equipment))
	})
	return _c
}

func (_c *MockEquipmentRepository_Update_Call) Return(_a0 error) *MockEquipmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Equipment) error) *MockEquipmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEquipmentRepository creates a new instance of MockEquipmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEquipmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEquipmentRepository {
	mock := &MockEquipmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
