// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repository

import (
	context "context"
	entity "medical-webhook/internal/domain/line/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockBrandRepository is an autogenerated mock type for the BrandRepository type
type MockBrandRepository struct {
	mock.Mock
}

type MockBrandRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrandRepository) EXPECT() *MockBrandRepository_Expecter {
	return &MockBrandRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, brand
func (_m *MockBrandRepository) Create(ctx context.Context, brand *entity.Brand) error {
	ret := _m.Called(ctx, brand)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Brand) error); ok {
		r0 = rf(ctx, brand)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBrandRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBrandRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - brand *entity.Brand
func (_e *MockBrandRepository_Expecter) Create(ctx interface{}, brand interface{}) *MockBrandRepository_Create_Call {
	return &MockBrandRepository_Create_Call{Call: _e.mock.On("Create", ctx, brand)}
}

func (_c *MockBrandRepository_Create_Call) Run(run func(ctx context.Context, brand *entity.Brand)) *MockBrandRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Brand))
	})
	return _c
}

func (_c *MockBrandRepository_Create_Call) Return(_a0 error) *MockBrandRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBrandRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Brand) error) *MockBrandRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBrandRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBrandRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBrandRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBrandRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockBrandRepository_Delete_Call {
	return &MockBrandRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBrandRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockBrandRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBrandRepository_Delete_Call) Return(_a0 error) *MockBrandRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBrandRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockBrandRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockBrandRepository) FindAll(ctx context.Context) ([]entity.Brand, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Brand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Brand, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Brand); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrandRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBrandRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBrandRepository_Expecter) FindAll(ctx interface{}) *MockBrandRepository_FindAll_Call {
	return &MockBrandRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockBrandRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockBrandRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBrandRepository_FindAll_Call) Return(_a0 []entity.Brand, _a1 error) *MockBrandRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrandRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.Brand, error)) *MockBrandRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockBrandRepository) FindByID(ctx context.Context, id uint) (*entity.Brand, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Brand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Brand, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Brand); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrandRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBrandRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBrandRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockBrandRepository_FindByID_Call {
	return &MockBrandRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBrandRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockBrandRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBrandRepository_FindByID_Call) Return(_a0 *entity.Brand, _a1 error) *MockBrandRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrandRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Brand, error)) *MockBrandRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockBrandRepository) FindByName(ctx context.Context, name string) (*entity.Brand, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.Brand
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Brand, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Brand); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Brand)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBrandRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockBrandRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockBrandRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockBrandRepository_FindByName_Call {
	return &MockBrandRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockBrandRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockBrandRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBrandRepository_FindByName_Call) Return(_a0 *entity.Brand, _a1 error) *MockBrandRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBrandRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*entity.Brand, error)) *MockBrandRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, brand
func (_m *MockBrandRepository) Update(ctx context.Context, brand *entity.Brand) error {
	ret := _m.Called(ctx, brand)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Brand) error); ok {
		r0 = rf(ctx, brand)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBrandRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBrandRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - brand *entity.Brand
func (_e *MockBrandRepository_Expecter) Update(ctx interface{}, brand interface{}) *MockBrandRepository_Update_Call {
	return &MockBrandRepository_Update_Call{Call: _e.mock.On("Update", ctx, brand)}
}

func (_c *MockBrandRepository_Update_Call) Run(run func(ctx context.Context, brand *entity.Brand)) *MockBrandRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Brand))
	})
	return _c
}

func (_c *MockBrandRepository_Update_Call) Return(_a0 error) *MockBrandRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBrandRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Brand) error) *MockBrandRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBrandRepository creates a new instance of MockBrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrandRepository {
	mock := &MockBrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
