// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repository

import (
	context "context"
	entity "medical-webhook/internal/domain/line/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockEquipmentModelRepository is an autogenerated mock type for the EquipmentModelRepository type
type MockEquipmentModelRepository struct {
	mock.Mock
}

type MockEquipmentModelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEquipmentModelRepository) EXPECT() *MockEquipmentModelRepository_Expecter {
	return &MockEquipmentModelRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, model
func (_m *MockEquipmentModelRepository) Create(ctx context.Context, model *entity.EquipmentModel) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.EquipmentModel) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentModelRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEquipmentModelRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model *entity.EquipmentModel
func (_e *MockEquipmentModelRepository_Expecter) Create(ctx interface{}, model interface{}) *MockEquipmentModelRepository_Create_Call {
	return &MockEquipmentModelRepository_Create_Call{Call: _e.mock.On("Create", ctx, model)}
}

func (_c *MockEquipmentModelRepository_Create_Call) Run(run func(ctx context.Context, model *entity.EquipmentModel)) *MockEquipmentModelRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.EquipmentModel))
	})
	return _c
}

func (_c *MockEquipmentModelRepository_Create_Call) Return(_a0 error) *MockEquipmentModelRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentModelRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.EquipmentModel) error) *MockEquipmentModelRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockEquipmentModelRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentModelRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEquipmentModelRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEquipmentModelRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockEquipmentModelRepository_Delete_Call {
	return &MockEquipmentModelRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEquipmentModelRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockEquipmentModelRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentModelRepository_Delete_Call) Return(_a0 error) *MockEquipmentModelRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentModelRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockEquipmentModelRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockEquipmentModelRepository) FindAll(ctx context.Context) ([]entity.EquipmentModel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.EquipmentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.EquipmentModel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.EquipmentModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EquipmentModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentModelRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockEquipmentModelRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentModelRepository_Expecter) FindAll(ctx interface{}) *MockEquipmentModelRepository_FindAll_Call {
	return &MockEquipmentModelRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockEquipmentModelRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockEquipmentModelRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEquipmentModelRepository_FindAll_Call) Return(_a0 []entity.EquipmentModel, _a1 error) *MockEquipmentModelRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentModelRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.EquipmentModel, error)) *MockEquipmentModelRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBrandCategoryModel provides a mock function with given fields: ctx, brandID, categoryID, modelName
func (_m *MockEquipmentModelRepository) FindByBrandCategoryModel(ctx context.Context, brandID uint, categoryID uint, modelName string) (*entity.EquipmentModel, error) {
	ret := _m.Called(ctx, brandID, categoryID, modelName)

	if len(ret) == 0 {
		panic("no return value specified for FindByBrandCategoryModel")
	}

	var r0 *entity.EquipmentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) (*entity.EquipmentModel, error)); ok {
		return rf(ctx, brandID, categoryID, modelName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) *entity.EquipmentModel); ok {
		r0 = rf(ctx, brandID, categoryID, modelName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EquipmentModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = rf(ctx, brandID, categoryID, modelName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentModelRepository_FindByBrandCategoryModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBrandCategoryModel'
type MockEquipmentModelRepository_FindByBrandCategoryModel_Call struct {
	*mock.Call
}

// FindByBrandCategoryModel is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID uint
//   - categoryID uint
//   - modelName string
func (_e *MockEquipmentModelRepository_Expecter) FindByBrandCategoryModel(ctx interface{}, brandID interface{}, categoryID interface{}, modelName interface{}) *MockEquipmentModelRepository_FindByBrandCategoryModel_Call {
	return &MockEquipmentModelRepository_FindByBrandCategoryModel_Call{Call: _e.mock.On("FindByBrandCategoryModel", ctx, brandID, categoryID, modelName)}
}

func (_c *MockEquipmentModelRepository_FindByBrandCategoryModel_Call) Run(run func(ctx context.Context, brandID uint, categoryID uint, modelName string)) *MockEquipmentModelRepository_FindByBrandCategoryModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(string))
	})
	return _c
}

func (_c *MockEquipmentModelRepository_FindByBrandCategoryModel_Call) Return(_a0 *entity.EquipmentModel, _a1 error) *MockEquipmentModelRepository_FindByBrandCategoryModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentModelRepository_FindByBrandCategoryModel_Call) RunAndReturn(run func(context.Context, uint, uint, string) (*entity.EquipmentModel, error)) *MockEquipmentModelRepository_FindByBrandCategoryModel_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBrandID provides a mock function with given fields: ctx, brandID
func (_m *MockEquipmentModelRepository) FindByBrandID(ctx context.Context, brandID uint) ([]entity.EquipmentModel, error) {
	ret := _m.Called(ctx, brandID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBrandID")
	}

	var r0 []entity.EquipmentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entity.EquipmentModel, error)); ok {
		return rf(ctx, brandID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entity.EquipmentModel); ok {
		r0 = rf(ctx, brandID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EquipmentModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, brandID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentModelRepository_FindByBrandID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBrandID'
type MockEquipmentModelRepository_FindByBrandID_Call struct {
	*mock.Call
}

// FindByBrandID is a helper method to define mock.On call
//   - ctx context.Context
//   - brandID uint
func (_e *MockEquipmentModelRepository_Expecter) FindByBrandID(ctx interface{}, brandID interface{}) *MockEquipmentModelRepository_FindByBrandID_Call {
	return &MockEquipmentModelRepository_FindByBrandID_Call{Call: _e.mock.On("FindByBrandID", ctx, brandID)}
}

func (_c *MockEquipmentModelRepository_FindByBrandID_Call) Run(run func(ctx context.Context, brandID uint)) *MockEquipmentModelRepository_FindByBrandID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentModelRepository_FindByBrandID_Call) Return(_a0 []entity.EquipmentModel, _a1 error) *MockEquipmentModelRepository_FindByBrandID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentModelRepository_FindByBrandID_Call) RunAndReturn(run func(context.Context, uint) ([]entity.EquipmentModel, error)) *MockEquipmentModelRepository_FindByBrandID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCategoryID provides a mock function with given fields: ctx, categoryID
func (_m *MockEquipmentModelRepository) FindByCategoryID(ctx context.Context, categoryID uint) ([]entity.EquipmentModel, error) {
	ret := _m.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCategoryID")
	}

	var r0 []entity.EquipmentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entity.EquipmentModel, error)); ok {
		return rf(ctx, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entity.EquipmentModel); ok {
		r0 = rf(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EquipmentModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentModelRepository_FindByCategoryID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCategoryID'
type MockEquipmentModelRepository_FindByCategoryID_Call struct {
	*mock.Call
}

// FindByCategoryID is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID uint
func (_e *MockEquipmentModelRepository_Expecter) FindByCategoryID(ctx interface{}, categoryID interface{}) *MockEquipmentModelRepository_FindByCategoryID_Call {
	return &MockEquipmentModelRepository_FindByCategoryID_Call{Call: _e.mock.On("FindByCategoryID", ctx, categoryID)}
}

func (_c *MockEquipmentModelRepository_FindByCategoryID_Call) Run(run func(ctx context.Context, categoryID uint)) *MockEquipmentModelRepository_FindByCategoryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentModelRepository_FindByCategoryID_Call) Return(_a0 []entity.EquipmentModel, _a1 error) *MockEquipmentModelRepository_FindByCategoryID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentModelRepository_FindByCategoryID_Call) RunAndReturn(run func(context.Context, uint) ([]entity.EquipmentModel, error)) *MockEquipmentModelRepository_FindByCategoryID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockEquipmentModelRepository) FindByID(ctx context.Context, id uint) (*entity.EquipmentModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.EquipmentModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.EquipmentModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.EquipmentModel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EquipmentModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentModelRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockEquipmentModelRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEquipmentModelRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockEquipmentModelRepository_FindByID_Call {
	return &MockEquipmentModelRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockEquipmentModelRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockEquipmentModelRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentModelRepository_FindByID_Call) Return(_a0 *entity.EquipmentModel, _a1 error) *MockEquipmentModelRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentModelRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.EquipmentModel, error)) *MockEquipmentModelRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, model
func (_m *MockEquipmentModelRepository) Update(ctx context.Context, model *entity.EquipmentModel) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.EquipmentModel) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentModelRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEquipmentModelRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model *entity.EquipmentModel
func (_e *MockEquipmentModelRepository_Expecter) Update(ctx interface{}, model interface{}) *MockEquipmentModelRepository_Update_Call {
	return &MockEquipmentModelRepository_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockEquipmentModelRepository_Update_Call) Run(run func(ctx context.Context, model *entity.EquipmentModel)) *MockEquipmentModelRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.EquipmentModel))
	})
	return _c
}

func (_c *MockEquipmentModelRepository_Update_Call) Return(_a0 error) *MockEquipmentModelRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentModelRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.EquipmentModel) error) *MockEquipmentModelRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEquipmentModelRepository creates a new instance of MockEquipmentModelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEquipmentModelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEquipmentModelRepository {
	mock := &MockEquipmentModelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
