// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repository

import (
	entity "medical-webhook/internal/domain/line/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockTicketRepository is an autogenerated mock type for the TicketRepository type
type MockTicketRepository struct {
	mock.Mock
}

type MockTicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketRepository) EXPECT() *MockTicketRepository_Expecter {
	return &MockTicketRepository_Expecter{mock: &_m.Mock}
}

// CreateTicket provides a mock function with given fields: ticket
func (_m *MockTicketRepository) CreateTicket(ticket *entity.Ticket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Ticket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketRepository_CreateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicket'
type MockTicketRepository_CreateTicket_Call struct {
	*mock.Call
}

// CreateTicket is a helper method to define mock.On call
//   - ticket *entity.Ticket
func (_e *MockTicketRepository_Expecter) CreateTicket(ticket interface{}) *MockTicketRepository_CreateTicket_Call {
	return &MockTicketRepository_CreateTicket_Call{Call: _e.mock.On("CreateTicket", ticket)}
}

func (_c *MockTicketRepository_CreateTicket_Call) Run(run func(ticket *entity.Ticket)) *MockTicketRepository_CreateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Ticket))
	})
	return _c
}

func (_c *MockTicketRepository_CreateTicket_Call) Return(_a0 error) *MockTicketRepository_CreateTicket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketRepository_CreateTicket_Call) RunAndReturn(run func(*entity.Ticket) error) *MockTicketRepository_CreateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingTicketByEquipmentAndUser provides a mock function with given fields: equipmentID, lineUserID
func (_m *MockTicketRepository) FindPendingTicketByEquipmentAndUser(equipmentID uint, lineUserID string) (*entity.Ticket, error) {
	ret := _m.Called(equipmentID, lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingTicketByEquipmentAndUser")
	}

	var r0 *entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) (*entity.Ticket, error)); ok {
		return rf(equipmentID, lineUserID)
	}
	if rf, ok := ret.Get(0).(func(uint, string) *entity.Ticket); ok {
		r0 = rf(equipmentID, lineUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(equipmentID, lineUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingTicketByEquipmentAndUser'
type MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call struct {
	*mock.Call
}

// FindPendingTicketByEquipmentAndUser is a helper method to define mock.On call
//   - equipmentID uint
//   - lineUserID string
func (_e *MockTicketRepository_Expecter) FindPendingTicketByEquipmentAndUser(equipmentID interface{}, lineUserID interface{}) *MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call {
	return &MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call{Call: _e.mock.On("FindPendingTicketByEquipmentAndUser", equipmentID, lineUserID)}
}

func (_c *MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call) Run(run func(equipmentID uint, lineUserID string)) *MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call) Return(_a0 *entity.Ticket, _a1 error) *MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call) RunAndReturn(run func(uint, string) (*entity.Ticket, error)) *MockTicketRepository_FindPendingTicketByEquipmentAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindTicketByID provides a mock function with given fields: id
func (_m *MockTicketRepository) FindTicketByID(id uint) (*entity.Ticket, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindTicketByID")
	}

	var r0 *entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entity.Ticket, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entity.Ticket); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_FindTicketByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTicketByID'
type MockTicketRepository_FindTicketByID_Call struct {
	*mock.Call
}

// FindTicketByID is a helper method to define mock.On call
//   - id uint
func (_e *MockTicketRepository_Expecter) FindTicketByID(id interface{}) *MockTicketRepository_FindTicketByID_Call {
	return &MockTicketRepository_FindTicketByID_Call{Call: _e.mock.On("FindTicketByID", id)}
}

func (_c *MockTicketRepository_FindTicketByID_Call) Run(run func(id uint)) *MockTicketRepository_FindTicketByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockTicketRepository_FindTicketByID_Call) Return(_a0 *entity.Ticket, _a1 error) *MockTicketRepository_FindTicketByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_FindTicketByID_Call) RunAndReturn(run func(uint) (*entity.Ticket, error)) *MockTicketRepository_FindTicketByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindTicketByNo provides a mock function with given fields: ticketNo
func (_m *MockTicketRepository) FindTicketByNo(ticketNo string) (*entity.Ticket, error) {
	ret := _m.Called(ticketNo)

	if len(ret) == 0 {
		panic("no return value specified for FindTicketByNo")
	}

	var r0 *entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.Ticket, error)); ok {
		return rf(ticketNo)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.Ticket); ok {
		r0 = rf(ticketNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ticketNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_FindTicketByNo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTicketByNo'
type MockTicketRepository_FindTicketByNo_Call struct {
	*mock.Call
}

// FindTicketByNo is a helper method to define mock.On call
//   - ticketNo string
func (_e *MockTicketRepository_Expecter) FindTicketByNo(ticketNo interface{}) *MockTicketRepository_FindTicketByNo_Call {
	return &MockTicketRepository_FindTicketByNo_Call{Call: _e.mock.On("FindTicketByNo", ticketNo)}
}

func (_c *MockTicketRepository_FindTicketByNo_Call) Run(run func(ticketNo string)) *MockTicketRepository_FindTicketByNo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTicketRepository_FindTicketByNo_Call) Return(_a0 *entity.Ticket, _a1 error) *MockTicketRepository_FindTicketByNo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_FindTicketByNo_Call) RunAndReturn(run func(string) (*entity.Ticket, error)) *MockTicketRepository_FindTicketByNo_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTickets provides a mock function with given fields: page, limit, status, priority, search, sortBy, sortDir
func (_m *MockTicketRepository) GetAllTickets(page int, limit int, status string, priority string, search string, sortBy string, sortDir string) ([]entity.Ticket, int64, error) {
	ret := _m.Called(page, limit, status, priority, search, sortBy, sortDir)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTickets")
	}

	var r0 []entity.Ticket
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string, string, string, string, string) ([]entity.Ticket, int64, error)); ok {
		return rf(page, limit, status, priority, search, sortBy, sortDir)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string, string, string, string) []entity.Ticket); ok {
		r0 = rf(page, limit, status, priority, search, sortBy, sortDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string, string, string, string) int64); ok {
		r1 = rf(page, limit, status, priority, search, sortBy, sortDir)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string, string, string, string, string) error); ok {
		r2 = rf(page, limit, status, priority, search, sortBy, sortDir)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTicketRepository_GetAllTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTickets'
type MockTicketRepository_GetAllTickets_Call struct {
	*mock.Call
}

// GetAllTickets is a helper method to define mock.On call
//   - page int
//   - limit int
//   - status string
//   - priority string
//   - search string
//   - sortBy string
//   - sortDir string
func (_e *MockTicketRepository_Expecter) GetAllTickets(page interface{}, limit interface{}, status interface{}, priority interface{}, search interface{}, sortBy interface{}, sortDir interface{}) *MockTicketRepository_GetAllTickets_Call {
	return &MockTicketRepository_GetAllTickets_Call{Call: _e.mock.On("GetAllTickets", page, limit, status, priority, search, sortBy, sortDir)}
}

func (_c *MockTicketRepository_GetAllTickets_Call) Run(run func(page int, limit int, status string, priority string, search string, sortBy string, sortDir string)) *MockTicketRepository_GetAllTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockTicketRepository_GetAllTickets_Call) Return(_a0 []entity.Ticket, _a1 int64, _a2 error) *MockTicketRepository_GetAllTickets_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTicketRepository_GetAllTickets_Call) RunAndReturn(run func(int, int, string, string, string, string, string) ([]entity.Ticket, int64, error)) *MockTicketRepository_GetAllTickets_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestTicketNumber provides a mock function with given fields: year
func (_m *MockTicketRepository) GetLatestTicketNumber(year int) (string, error) {
	ret := _m.Called(year)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTicketNumber")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(year)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(year)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_GetLatestTicketNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestTicketNumber'
type MockTicketRepository_GetLatestTicketNumber_Call struct {
	*mock.Call
}

// GetLatestTicketNumber is a helper method to define mock.On call
//   - year int
func (_e *MockTicketRepository_Expecter) GetLatestTicketNumber(year interface{}) *MockTicketRepository_GetLatestTicketNumber_Call {
	return &MockTicketRepository_GetLatestTicketNumber_Call{Call: _e.mock.On("GetLatestTicketNumber", year)}
}

func (_c *MockTicketRepository_GetLatestTicketNumber_Call) Run(run func(year int)) *MockTicketRepository_GetLatestTicketNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTicketRepository_GetLatestTicketNumber_Call) Return(_a0 string, _a1 error) *MockTicketRepository_GetLatestTicketNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_GetLatestTicketNumber_Call) RunAndReturn(run func(int) (string, error)) *MockTicketRepository_GetLatestTicketNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentTickets provides a mock function with given fields: limit
func (_m *MockTicketRepository) GetRecentTickets(limit int) ([]entity.Ticket, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentTickets")
	}

	var r0 []entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]entity.Ticket, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []entity.Ticket); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_GetRecentTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentTickets'
type MockTicketRepository_GetRecentTickets_Call struct {
	*mock.Call
}

// GetRecentTickets is a helper method to define mock.On call
//   - limit int
func (_e *MockTicketRepository_Expecter) GetRecentTickets(limit interface{}) *MockTicketRepository_GetRecentTickets_Call {
	return &MockTicketRepository_GetRecentTickets_Call{Call: _e.mock.On("GetRecentTickets", limit)}
}

func (_c *MockTicketRepository_GetRecentTickets_Call) Run(run func(limit int)) *MockTicketRepository_GetRecentTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTicketRepository_GetRecentTickets_Call) Return(_a0 []entity.Ticket, _a1 error) *MockTicketRepository_GetRecentTickets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_GetRecentTickets_Call) RunAndReturn(run func(int) ([]entity.Ticket, error)) *MockTicketRepository_GetRecentTickets_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicketStats provides a mock function with no fields
func (_m *MockTicketRepository) GetTicketStats() (int64, int64, int64, int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTicketStats")
	}

	var r0 int64
	var r1 int64
	var r2 int64
	var r3 int64
	var r4 error
	if rf, ok := ret.Get(0).(func() (int64, int64, int64, int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() int64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func() int64); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func() int64); ok {
		r3 = rf()
	} else {
		r3 = ret.Get(3).(int64)
	}

	if rf, ok := ret.Get(4).(func() error); ok {
		r4 = rf()
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MockTicketRepository_GetTicketStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicketStats'
type MockTicketRepository_GetTicketStats_Call struct {
	*mock.Call
}

// GetTicketStats is a helper method to define mock.On call
func (_e *MockTicketRepository_Expecter) GetTicketStats() *MockTicketRepository_GetTicketStats_Call {
	return &MockTicketRepository_GetTicketStats_Call{Call: _e.mock.On("GetTicketStats")}
}

func (_c *MockTicketRepository_GetTicketStats_Call) Run(run func()) *MockTicketRepository_GetTicketStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTicketRepository_GetTicketStats_Call) Return(total int64, inProgress int64, completed int64, sendToOutsource int64, err error) *MockTicketRepository_GetTicketStats_Call {
	_c.Call.Return(total, inProgress, completed, sendToOutsource, err)
	return _c
}

func (_c *MockTicketRepository_GetTicketStats_Call) RunAndReturn(run func() (int64, int64, int64, int64, error)) *MockTicketRepository_GetTicketStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicketsByEquipmentID provides a mock function with given fields: equipmentID
func (_m *MockTicketRepository) GetTicketsByEquipmentID(equipmentID uint) ([]entity.Ticket, error) {
	ret := _m.Called(equipmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTicketsByEquipmentID")
	}

	var r0 []entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]entity.Ticket, error)); ok {
		return rf(equipmentID)
	}
	if rf, ok := ret.Get(0).(func(uint) []entity.Ticket); ok {
		r0 = rf(equipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(equipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_GetTicketsByEquipmentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicketsByEquipmentID'
type MockTicketRepository_GetTicketsByEquipmentID_Call struct {
	*mock.Call
}

// GetTicketsByEquipmentID is a helper method to define mock.On call
//   - equipmentID uint
func (_e *MockTicketRepository_Expecter) GetTicketsByEquipmentID(equipmentID interface{}) *MockTicketRepository_GetTicketsByEquipmentID_Call {
	return &MockTicketRepository_GetTicketsByEquipmentID_Call{Call: _e.mock.On("GetTicketsByEquipmentID", equipmentID)}
}

func (_c *MockTicketRepository_GetTicketsByEquipmentID_Call) Run(run func(equipmentID uint)) *MockTicketRepository_GetTicketsByEquipmentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockTicketRepository_GetTicketsByEquipmentID_Call) Return(_a0 []entity.Ticket, _a1 error) *MockTicketRepository_GetTicketsByEquipmentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_GetTicketsByEquipmentID_Call) RunAndReturn(run func(uint) ([]entity.Ticket, error)) *MockTicketRepository_GetTicketsByEquipmentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicketsByLineUserID provides a mock function with given fields: lineUserID
func (_m *MockTicketRepository) GetTicketsByLineUserID(lineUserID string) ([]entity.Ticket, error) {
	ret := _m.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetTicketsByLineUserID")
	}

	var r0 []entity.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Ticket, error)); ok {
		return rf(lineUserID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Ticket); ok {
		r0 = rf(lineUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lineUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_GetTicketsByLineUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicketsByLineUserID'
type MockTicketRepository_GetTicketsByLineUserID_Call struct {
	*mock.Call
}

// GetTicketsByLineUserID is a helper method to define mock.On call
//   - lineUserID string
func (_e *MockTicketRepository_Expecter) GetTicketsByLineUserID(lineUserID interface{}) *MockTicketRepository_GetTicketsByLineUserID_Call {
	return &MockTicketRepository_GetTicketsByLineUserID_Call{Call: _e.mock.On("GetTicketsByLineUserID", lineUserID)}
}

func (_c *MockTicketRepository_GetTicketsByLineUserID_Call) Run(run func(lineUserID string)) *MockTicketRepository_GetTicketsByLineUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTicketRepository_GetTicketsByLineUserID_Call) Return(_a0 []entity.Ticket, _a1 error) *MockTicketRepository_GetTicketsByLineUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_GetTicketsByLineUserID_Call) RunAndReturn(run func(string) ([]entity.Ticket, error)) *MockTicketRepository_GetTicketsByLineUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTicket provides a mock function with given fields: ticket
func (_m *MockTicketRepository) UpdateTicket(ticket *entity.Ticket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTicket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Ticket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketRepository_UpdateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTicket'
type MockTicketRepository_UpdateTicket_Call struct {
	*mock.Call
}

// UpdateTicket is a helper method to define mock.On call
//   - ticket *entity.Ticket
func (_e *MockTicketRepository_Expecter) UpdateTicket(ticket interface{}) *MockTicketRepository_UpdateTicket_Call {
	return &MockTicketRepository_UpdateTicket_Call{Call: _e.mock.On("UpdateTicket", ticket)}
}

func (_c *MockTicketRepository_UpdateTicket_Call) Run(run func(ticket *entity.Ticket)) *MockTicketRepository_UpdateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Ticket))
	})
	return _c
}

func (_c *MockTicketRepository_UpdateTicket_Call) Return(_a0 error) *MockTicketRepository_UpdateTicket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketRepository_UpdateTicket_Call) RunAndReturn(run func(*entity.Ticket) error) *MockTicketRepository_UpdateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTicketStatus provides a mock function with given fields: ticketID, newStatus, note
func (_m *MockTicketRepository) UpdateTicketStatus(ticketID uint, newStatus entity.TicketStatus, note string) error {
	ret := _m.Called(ticketID, newStatus, note)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTicketStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, entity.TicketStatus, string) error); ok {
		r0 = rf(ticketID, newStatus, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketRepository_UpdateTicketStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTicketStatus'
type MockTicketRepository_UpdateTicketStatus_Call struct {
	*mock.Call
}

// UpdateTicketStatus is a helper method to define mock.On call
//   - ticketID uint
//   - newStatus entity.TicketStatus
//   - note string
func (_e *MockTicketRepository_Expecter) UpdateTicketStatus(ticketID interface{}, newStatus interface{}, note interface{}) *MockTicketRepository_UpdateTicketStatus_Call {
	return &MockTicketRepository_UpdateTicketStatus_Call{Call: _e.mock.On("UpdateTicketStatus", ticketID, newStatus, note)}
}

func (_c *MockTicketRepository_UpdateTicketStatus_Call) Run(run func(ticketID uint, newStatus entity.TicketStatus, note string)) *MockTicketRepository_UpdateTicketStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(entity.TicketStatus), args[2].(string))
	})
	return _c
}

func (_c *MockTicketRepository_UpdateTicketStatus_Call) Return(_a0 error) *MockTicketRepository_UpdateTicketStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketRepository_UpdateTicketStatus_Call) RunAndReturn(run func(uint, entity.TicketStatus, string) error) *MockTicketRepository_UpdateTicketStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTicketRepository creates a new instance of MockTicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketRepository {
	mock := &MockTicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
