// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_repository

import (
	context "context"
	entity "medical-webhook/internal/domain/line/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockEquipmentCategoryRepository is an autogenerated mock type for the EquipmentCategoryRepository type
type MockEquipmentCategoryRepository struct {
	mock.Mock
}

type MockEquipmentCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEquipmentCategoryRepository) EXPECT() *MockEquipmentCategoryRepository_Expecter {
	return &MockEquipmentCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, category
func (_m *MockEquipmentCategoryRepository) Create(ctx context.Context, category *entity.EquipmentCategory) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.EquipmentCategory) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEquipmentCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *entity.EquipmentCategory
func (_e *MockEquipmentCategoryRepository_Expecter) Create(ctx interface{}, category interface{}) *MockEquipmentCategoryRepository_Create_Call {
	return &MockEquipmentCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockEquipmentCategoryRepository_Create_Call) Run(run func(ctx context.Context, category *entity.EquipmentCategory)) *MockEquipmentCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.EquipmentCategory))
	})
	return _c
}

func (_c *MockEquipmentCategoryRepository_Create_Call) Return(_a0 error) *MockEquipmentCategoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentCategoryRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.EquipmentCategory) error) *MockEquipmentCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockEquipmentCategoryRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEquipmentCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEquipmentCategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockEquipmentCategoryRepository_Delete_Call {
	return &MockEquipmentCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEquipmentCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockEquipmentCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentCategoryRepository_Delete_Call) Return(_a0 error) *MockEquipmentCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentCategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockEquipmentCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockEquipmentCategoryRepository) FindAll(ctx context.Context) ([]entity.EquipmentCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.EquipmentCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.EquipmentCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.EquipmentCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EquipmentCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentCategoryRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockEquipmentCategoryRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentCategoryRepository_Expecter) FindAll(ctx interface{}) *MockEquipmentCategoryRepository_FindAll_Call {
	return &MockEquipmentCategoryRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockEquipmentCategoryRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockEquipmentCategoryRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEquipmentCategoryRepository_FindAll_Call) Return(_a0 []entity.EquipmentCategory, _a1 error) *MockEquipmentCategoryRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentCategoryRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.EquipmentCategory, error)) *MockEquipmentCategoryRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByECRIRisk provides a mock function with given fields: ctx, risk
func (_m *MockEquipmentCategoryRepository) FindByECRIRisk(ctx context.Context, risk entity.ECRIRiskLevel) ([]entity.EquipmentCategory, error) {
	ret := _m.Called(ctx, risk)

	if len(ret) == 0 {
		panic("no return value specified for FindByECRIRisk")
	}

	var r0 []entity.EquipmentCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ECRIRiskLevel) ([]entity.EquipmentCategory, error)); ok {
		return rf(ctx, risk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ECRIRiskLevel) []entity.EquipmentCategory); ok {
		r0 = rf(ctx, risk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EquipmentCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ECRIRiskLevel) error); ok {
		r1 = rf(ctx, risk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentCategoryRepository_FindByECRIRisk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByECRIRisk'
type MockEquipmentCategoryRepository_FindByECRIRisk_Call struct {
	*mock.Call
}

// FindByECRIRisk is a helper method to define mock.On call
//   - ctx context.Context
//   - risk entity.ECRIRiskLevel
func (_e *MockEquipmentCategoryRepository_Expecter) FindByECRIRisk(ctx interface{}, risk interface{}) *MockEquipmentCategoryRepository_FindByECRIRisk_Call {
	return &MockEquipmentCategoryRepository_FindByECRIRisk_Call{Call: _e.mock.On("FindByECRIRisk", ctx, risk)}
}

func (_c *MockEquipmentCategoryRepository_FindByECRIRisk_Call) Run(run func(ctx context.Context, risk entity.ECRIRiskLevel)) *MockEquipmentCategoryRepository_FindByECRIRisk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ECRIRiskLevel))
	})
	return _c
}

func (_c *MockEquipmentCategoryRepository_FindByECRIRisk_Call) Return(_a0 []entity.EquipmentCategory, _a1 error) *MockEquipmentCategoryRepository_FindByECRIRisk_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentCategoryRepository_FindByECRIRisk_Call) RunAndReturn(run func(context.Context, entity.ECRIRiskLevel) ([]entity.EquipmentCategory, error)) *MockEquipmentCategoryRepository_FindByECRIRisk_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockEquipmentCategoryRepository) FindByID(ctx context.Context, id uint) (*entity.EquipmentCategory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.EquipmentCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.EquipmentCategory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.EquipmentCategory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EquipmentCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentCategoryRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockEquipmentCategoryRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEquipmentCategoryRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockEquipmentCategoryRepository_FindByID_Call {
	return &MockEquipmentCategoryRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockEquipmentCategoryRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockEquipmentCategoryRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEquipmentCategoryRepository_FindByID_Call) Return(_a0 *entity.EquipmentCategory, _a1 error) *MockEquipmentCategoryRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentCategoryRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.EquipmentCategory, error)) *MockEquipmentCategoryRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockEquipmentCategoryRepository) FindByName(ctx context.Context, name string) (*entity.EquipmentCategory, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.EquipmentCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.EquipmentCategory, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.EquipmentCategory); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EquipmentCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEquipmentCategoryRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockEquipmentCategoryRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockEquipmentCategoryRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockEquipmentCategoryRepository_FindByName_Call {
	return &MockEquipmentCategoryRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockEquipmentCategoryRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockEquipmentCategoryRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEquipmentCategoryRepository_FindByName_Call) Return(_a0 *entity.EquipmentCategory, _a1 error) *MockEquipmentCategoryRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEquipmentCategoryRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*entity.EquipmentCategory, error)) *MockEquipmentCategoryRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, category
func (_m *MockEquipmentCategoryRepository) Update(ctx context.Context, category *entity.EquipmentCategory) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.EquipmentCategory) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEquipmentCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEquipmentCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *entity.EquipmentCategory
func (_e *MockEquipmentCategoryRepository_Expecter) Update(ctx interface{}, category interface{}) *MockEquipmentCategoryRepository_Update_Call {
	return &MockEquipmentCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *MockEquipmentCategoryRepository_Update_Call) Run(run func(ctx context.Context, category *entity.EquipmentCategory)) *MockEquipmentCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.EquipmentCategory))
	})
	return _c
}

func (_c *MockEquipmentCategoryRepository_Update_Call) Return(_a0 error) *MockEquipmentCategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEquipmentCategoryRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.EquipmentCategory) error) *MockEquipmentCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEquipmentCategoryRepository creates a new instance of MockEquipmentCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEquipmentCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEquipmentCategoryRepository {
	mock := &MockEquipmentCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
