// Package exporturl builds and verifies signed URLs for the equipment expiry
// Excel export. The export link is embedded as a button in LINE Flex messages
// and opened in the user's browser without a bearer token, so it cannot sit
// behind the normal admin auth middleware. Instead each link carries an expiry
// timestamp and an HMAC signature: links generated by the server remain valid
// until they expire, but the endpoint cannot be reached by guessing the URL.
package exporturl

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"net/url"
	"strconv"
	"time"
)

// Path is the route the export handler is mounted on.
const Path = "/notifications/export/expiry"

// DefaultTTL is how long a generated link stays valid. Expiry alerts are
// seasonal (June/August) and a user may open the link days after receiving it,
// so the window is generous.
const DefaultTTL = 30 * 24 * time.Hour

var (
	// ErrNotConfigured is returned when Verify is called before Init.
	ErrNotConfigured = errors.New("export url signing not configured")
	// ErrExpired is returned when the link's exp timestamp is in the past.
	ErrExpired = errors.New("export link expired")
	// ErrInvalidSignature is returned when the signature does not match.
	ErrInvalidSignature = errors.New("invalid export link signature")
	// ErrInvalidExp is returned when the exp parameter is not a valid unix time.
	ErrInvalidExp = errors.New("invalid export link expiry")
)

// key is the HMAC secret. Package-level to match the codebase's existing style
// (db/redis clients are wired similarly) and so plain template functions can
// build links without threading a signer through every call.
var key []byte

// Init sets the signing secret. It should be called once at startup with a
// long, stable secret (e.g. the LINE channel secret).
func Init(secret string) {
	key = []byte(secret)
}

// deptString renders an optional department id the same way on both the signing
// and verifying sides ("" when absent).
func deptString(deptID *uint) string {
	if deptID == nil {
		return ""
	}
	return strconv.FormatUint(uint64(*deptID), 10)
}

// normalizeFilter mirrors the handler's default so a link built with an empty
// filter verifies against the "all" the handler reads back.
func normalizeFilter(filter string) string {
	if filter == "" {
		return "all"
	}
	return filter
}

// sign computes the HMAC over the canonical (dept, filter, exp) tuple.
func sign(dept, filter, exp string) string {
	mac := hmac.New(sha256.New, key)
	mac.Write([]byte(dept + "\n" + filter + "\n" + exp))
	return hex.EncodeToString(mac.Sum(nil))
}

// SignedURL returns the full download URL (baseURL + Path + signed query) valid
// for DefaultTTL from now. deptID may be nil (all departments); filter may be
// "" (treated as "all").
func SignedURL(baseURL string, deptID *uint, filter string) string {
	return signedURLAt(baseURL, deptID, filter, time.Now().Add(DefaultTTL))
}

func signedURLAt(baseURL string, deptID *uint, filter string, expiresAt time.Time) string {
	dept := deptString(deptID)
	filter = normalizeFilter(filter)
	exp := strconv.FormatInt(expiresAt.Unix(), 10)

	q := url.Values{}
	if dept != "" {
		q.Set("dept_id", dept)
	}
	q.Set("filter", filter)
	q.Set("exp", exp)
	q.Set("sig", sign(dept, filter, exp))

	return baseURL + Path + "?" + q.Encode()
}

// Verify checks a request's signature and expiry. dept is the raw dept_id query
// value ("" when absent), filter/exp/sig are the corresponding query values, and
// now is the current time (injected for testability).
func Verify(dept, filter, exp, sig string, now time.Time) error {
	if len(key) == 0 {
		return ErrNotConfigured
	}
	filter = normalizeFilter(filter)

	expUnix, err := strconv.ParseInt(exp, 10, 64)
	if err != nil {
		return ErrInvalidExp
	}
	if now.After(time.Unix(expUnix, 0)) {
		return ErrExpired
	}

	want := sign(dept, filter, exp)
	if !hmac.Equal([]byte(want), []byte(sig)) {
		return ErrInvalidSignature
	}
	return nil
}
