// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_event

import (
	context "context"
	event "medical-webhook/internal/domain/event"

	mock "github.com/stretchr/testify/mock"
)

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

type MockEventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBus) EXPECT() *MockEventBus_Expecter {
	return &MockEventBus_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockEventBus) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEventBus_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) Close() *MockEventBus_Close_Call {
	return &MockEventBus_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEventBus_Close_Call) Run(run func()) *MockEventBus_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_Close_Call) Return(_a0 error) *MockEventBus_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Close_Call) RunAndReturn(run func() error) *MockEventBus_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, _a1
func (_m *MockEventBus) Publish(ctx context.Context, _a1 event.Event) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Event) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventBus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 event.Event
func (_e *MockEventBus_Expecter) Publish(ctx interface{}, _a1 interface{}) *MockEventBus_Publish_Call {
	return &MockEventBus_Publish_Call{Call: _e.mock.On("Publish", ctx, _a1)}
}

func (_c *MockEventBus_Publish_Call) Run(run func(ctx context.Context, _a1 event.Event)) *MockEventBus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.Event))
	})
	return _c
}

func (_c *MockEventBus_Publish_Call) Return(_a0 error) *MockEventBus_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_Publish_Call) RunAndReturn(run func(context.Context, event.Event) error) *MockEventBus_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, eventTypes
func (_m *MockEventBus) Subscribe(ctx context.Context, eventTypes ...string) (<-chan event.Event, error) {
	_va := make([]interface{}, len(eventTypes))
	for _i := range eventTypes {
		_va[_i] = eventTypes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) (<-chan event.Event, error)); ok {
		return rf(ctx, eventTypes...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...string) <-chan event.Event); ok {
		r0 = rf(ctx, eventTypes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, eventTypes...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventBus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - eventTypes ...string
func (_e *MockEventBus_Expecter) Subscribe(ctx interface{}, eventTypes ...interface{}) *MockEventBus_Subscribe_Call {
	return &MockEventBus_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{ctx}, eventTypes...)...)}
}

func (_c *MockEventBus_Subscribe_Call) Run(run func(ctx context.Context, eventTypes ...string)) *MockEventBus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockEventBus_Subscribe_Call) Return(_a0 <-chan event.Event, _a1 error) *MockEventBus_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventBus_Subscribe_Call) RunAndReturn(run func(context.Context, ...string) (<-chan event.Event, error)) *MockEventBus_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventBus creates a new instance of MockEventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBus {
	mock := &MockEventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
